"""Audience-facing Gate 2 sample compositions. Narration is read from course.md."""
CHAT = '''<svg viewBox="0 0 80 80" aria-hidden="true"><path d="M12 13h56v42H36L20 68V55h-8z"/><path d="M24 28h32M24 39h23" fill="none"/></svg>'''

def scenario(text, title="A Singapore retailer's customer-service chatbot"):
    return f'<div class="scenario">{CHAT}<div><span class="case-id">HYPOTHETICAL EXAMPLE</span><h3>{title}</h3><p>{text}</p></div></div>'

def question(options, cls='legal-quiz'):
    rows=[]
    for i,(answer,feedback,correct) in enumerate(options):
        rows.append(f'<button type="button" class="mcq"'+(' data-correct' if correct else '')+f'><span class="letter">{chr(65+i)}</span><span><b>{answer}</b><span class="why">{feedback}</span></span></button>')
    return f'<div class="quiz {cls}" aria-label="Choose one answer">'+''.join(rows)+'<p class="verdict" aria-live="polite"></p></div>'

# Each tuple: course slide, kicker, heading, composition, source IDs.
SLIDES = [
(1,'','AI Governance Overview','''<div class="cover-main"><p class="cover-series">AI for Business Leaders · Online Series for ISCA</p><h1 class="cover-title">AI Governance Overview</h1><div class="cover-rule"></div><p class="cover-by">Ray Han, PhD (Computer Science, NTU)</p><p class="cover-role">Chief AI Trainer, HGT Consultancy Pte Ltd</p></div><div class="cover-foot"><span>Concepts · components · cases · implementation</span><span>30 minutes · recorded</span></div>''',[]),
(2,'THE LAUNCH DECISION','Would you approve the launch?',scenario('The supplier says its product follows Singapore’s Model AI Governance Framework.')+question([
('Approve the launch','Supplier alignment alone does not establish readiness.',False),
('Reject the proposal','The available facts do not justify permanent rejection.',False),
('Request more information','Withhold approval and obtain evidence about this deployment.',True)],'decision-quiz'),['R04']),
(3,'BEFORE APPROVAL','Four questions to answer first','''<ol class="q-list stagger"><li><b>Data*</b><span>What personal data will the chatbot collect or use?</span></li><li><b>Customer commitments</b><span>What commitments can it make to customers?</span></li><li><b>Jurisdictions</b><span>Which jurisdictions will it serve?</span></li><li><b>Accountability</b><span>Who will be accountable for its operation?</span></li></ol><p class="governance-purpose">Singapore’s Model AI Governance Framework is voluntary.<br>Applicable obligations under the PDPA remain binding.</p><p class="minor-note">*Direct PDPA relevance where personal data is involved. Other questions may also raise data-protection obligations.</p>''',['R04','R05']),
(4,'2024 SURVEY · UK FINANCIAL SERVICES','AI adoption and oversight in UK financial services','''<div class="stat-row"><div><p class="stat-fig">75%</p><p class="stat-unit">were already using AI</p><p class="stat-base">Of responding firms</p></div><div><p class="stat-fig">46%</p><p class="stat-unit">reported partial understanding of the AI they used</p><p class="stat-base">Survey respondents’ reported understanding</p></div><div><p class="stat-fig">⅓</p><p class="stat-unit">were third-party implementations</p><p class="stat-base">Of reported AI use cases</p></div></div><p class="minor-note">Sector-specific evidence. These figures do not measure how firms would answer the launch question.</p>''',['R06']),
(5,'','What is an AI system?','''<p class="definition">A machine-based system that infers from inputs how to produce predictions, content, recommendations or decisions — with varying autonomy, and outputs that can affect the real world.</p><div class="example-row stagger"><article><h4>Predictive model</h4><p>Estimates credit risk.</p></article><article><h4>Generative AI</h4><p>Produces a customer reply.</p></article><article><h4>AI agent</h4><p>Acts through software tools.</p></article></div>''',['R01']),
(6,'','What is AI governance?','''<p class="definition">The responsibilities, policies, decision processes and controls through which an organisation oversees AI it builds, buys or uses.</p><p class="definition-sub">It answers three questions.</p><div class="example-row stagger"><article><h4>Who decides?</h4><p>Who approves a use, on what evidence, and when must they reconsider?</p></article><article><h4>What could go wrong?</h4><p>What harm is possible, and which controls reduce it?</p></article><article><h4>What must we meet?</h4><p>Which legal and contractual obligations apply to this use?</p></article></div>''',['R02','R03']),
(7,'SCOPE','Governance covers the AI lifecycle','''<ol class="lifecycle stagger"><li><span class="step-no">01</span><h4>Define</h4><p>Purpose, benefit, affected people and acceptable limits.</p></li><li><span class="step-no">02</span><h4>Develop or procure</h4><p>Data, supplier dependencies and system evidence.</p></li><li><span class="step-no">03</span><h4>Test and approve</h4><p>Intended workflow, safeguards and deployment conditions.</p></li><li><span class="step-no">04</span><h4>Operate and review</h4><p>Outcomes, complaints, incidents and material changes.</p></li><li><span class="step-no">05</span><h4>Retire or replace</h4><p>Access, records and dependent workflows.</p></li></ol><p class="review-loop">Reassess whenever the model, data, users or operating context changes.</p>''',['R02','R03']),
(8,'COMPONENTS','Six components of organisational AI governance','''<div class="component-grid"><article class="component"><div><h4>Accountability and oversight</h4><p>Owner, approval authority and escalation.</p></div></article><article class="component"><div><h4>Inventory and impact assessment</h4><p>Uses, purposes, affected people and consequences.</p></div></article><article class="component"><div><h4>Data and supplier governance</h4><p>Privacy, quality, security and supplier responsibilities.</p></div></article><article class="component"><div><h4>Testing and human oversight</h4><p>Acceptable performance and effective intervention.</p></div></article><article class="component"><div><h4>Transparency and recourse</h4><p>Accurate explanations and usable review routes.</p></div></article><article class="component"><div><h4>Monitoring and improvement</h4><p>Outcomes, incidents, changes and retirement.</p></div></article></div><p class="minor-note">Teaching synthesis: connected components, with controls proportionate to the use and its consequences.</p>''',['R02','R03','R04']),
(9,'RESPONSIBILITIES','Who reviews an AI proposal before launch?','''<table class="roles"><thead><tr><th>Role</th><th>Question to resolve</th><th>Evidence before approval</th></tr></thead><tbody><tr><td>Business owner</td><td>What is the intended use and acceptable outcome?</td><td>Purpose, boundaries and affected people</td></tr><tr><td>Technical and data teams</td><td>Does the system work acceptably in this setting?</td><td>Test results, limitations and operating controls</td></tr><tr><td>Risk, legal and compliance</td><td>Which obligations apply, and are the safeguards adequate?</td><td>Applicability assessment and independent challenge</td></tr><tr><td>Accountable executive</td><td>Do the evidence and conditions justify deployment?</td><td>Approval record, residual risk and review triggers</td></tr></tbody></table><p class="minor-note">Illustrative responsibilities. The same functions remain involved during operation and material change.</p>''',['R02','R03']),
(10,'AS AT 13 SEPTEMBER 2026','AI governance across jurisdictions','''<div class="map-layout"><div class="map-stage">{{WORLD_MAP}}</div><div class="map-controls">{{MAP_CONTROLS}}</div><p class="map-detail">Select a jurisdiction to see its approach.</p></div><p class="minor-note">Assess the use, the affected people, the locations served, and whether the organisation is a provider or a deployer.</p>''',['R04','R07','R09','R24','R25']),
(11,'LEGAL EFFECT','Different instruments have different legal effects','''<div class="legal-row stagger-item"><h4>Binding requirements</h4><p>Acts, regulations and binding regulatory requirements create duties for the relevant activity.</p></div><div class="legal-row stagger-item"><h4>Supervisory expectations</h4><p>Guidance may explain existing law or inform supervisory assessment and corrective action.</p></div><div class="legal-row stagger-item"><h4>Voluntary frameworks</h4><p>Methods and guidance for organising controls. Contracts or policies may add commitments.</p></div><p class="minor-note">Several instruments may apply to one use. These are not three levels of risk.</p>''',['R04','R05','R10']),
(12,'AS AT 12 SEPTEMBER 2026','AI Governance in Singapore','''<div class="jurisdiction-grid"><article class="jurisdiction-panel"><p class="status">BINDING WITHIN SCOPE</p><h3>Existing legal obligations</h3><p>The PDPA governs relevant collection, use and disclosure of personal data, subject to scope and exceptions.</p><p>For the chatbot: review purposes, notification, protection and retention of customer information.</p><p>Assess other business obligations and relevant sector requirements.</p></article><article class="jurisdiction-panel"><p class="status">VOLUNTARY GUIDANCE</p><h3>Model AI Governance Framework</h3><p>Internal governance and responsibilities.</p><p>Human involvement and operations management.</p><p>Stakeholder communication.</p><p>The framework supports governance practices; it does not replace applicable law.</p></article></div>''',['R04','R05']),
(13,'AS AT 12 SEPTEMBER 2026','EU AI Act','''<p class="block-label">What the Act regulates</p><div class="eu-components stagger"><article><h4>Prohibited practices</h4><p>Uses the Act bans within its scope.</p></article><article><h4>High-risk systems</h4><p>Risk management, data, records and human oversight.</p></article><article><h4>General-purpose AI</h4><p>Separate obligations for model providers.</p></article><article><h4>Transparency</h4><p>Disclosure for specified AI interactions and content.</p></article></div><p class="block-label">When each part applies</p><ol class="timeline"><li><time>2 February 2025</time><p>Prohibitions</p><span class="timeline-status">APPLICABLE</span></li><li><time>2 August 2025</time><p>General-purpose AI provisions</p><span class="timeline-status">APPLICABLE</span></li><li><time>2 August 2026</time><p>General application, including Article 50</p><span class="timeline-status">APPLICABLE</span></li><li class="future"><time>2 December 2027</time><p>Annex III high-risk requirements</p><span class="timeline-status">NOT YET APPLICABLE</span></li><li class="future"><time>2 August 2028</time><p>Annex I product-related high-risk requirements</p><span class="timeline-status">NOT YET APPLICABLE</span></li></ol><p class="eu-note">Non-EU organisations can be in scope, including certain uses of AI outputs in the Union.</p>''',['R07','R08']),
(14,'AS AT 12 SEPTEMBER 2026','AI Governance in the United Kingdom','''<div class="jurisdiction-grid"><article class="jurisdiction-panel"><p class="status">EXISTING LEGAL FRAMEWORKS</p><h3>Identify the activity and regulator</h3><p>Data protection, equality and sector regulation may be relevant.</p><p>The ICO addresses data protection. Financial regulators oversee financial services.</p><p>Translate applicable requirements into responsibilities, controls and evidence for the AI use.</p></article><article class="jurisdiction-panel"><p class="status">2023 POLICY PRINCIPLES · NOT FIVE NEW STATUTORY DUTIES</p><h3>Principles for regulation</h3><p>Safety, security and robustness.<br>Appropriate transparency and explainability.</p><p>Fairness.<br>Accountability and governance.</p><p>Contestability and redress.</p></article></div>''',['R09','R11','R12']),
(16,'CHECK YOUR UNDERSTANDING','Does following a framework resolve the data issue?','''<p class="quiz-stem">The retailer collects contact details and purchase histories to personalise offers. It has not explained those purposes. Assume the PDPA notification obligation applies.</p><p class="minor-note">The supplier follows the Model AI Governance Framework and displays an AI label.</p>'''+question([
('Yes. Following the framework resolves it.','Framework alignment does not establish that the retailer met its obligation.',False),
('No. Address the applicable PDPA obligation before launch.','The retailer must explain the relevant data-use purposes.',True),
('Yes. The AI label is enough.','An AI label alone does not explain the data-use purposes.',False)]),['R04','R05']),
(18,'CASE STUDY · SINGAPORE','HSBC’s credit-assessment disclosures','''<div class="case-timeline"><article><h4>2018 · The access request</h4><p>An unsuccessful credit-card applicant sought HSBC’s internal evaluation report.</p><p>The bank supplied a report with specified information redacted.</p></article><article><h4>2021 · The PDPC decision</h4><p>The evaluative-purpose exception supported withholding specified data.</p><p>HSBC also supplied explanations of its AI/data practices and credit assessments.</p></article></div><blockquote class="case-quote"><p>“From the perspective of <mark>accountability and disclosure</mark> of policies and practices, HSBC had acquitted itself.”</p><cite>Deputy Commissioner for Personal Data Protection · paragraph 19</cite></blockquote><p class="minor-note">Lesson: prepare accurate explanations alongside the assessment of access rights and exceptions.</p>''',['R14']),
(26,'THE SAME FOUR QUESTIONS, ANSWERED','Would you approve the chatbot now?',scenario('The team has supplied evidence. Refund-policy answers have not passed the retailer’s acceptance tests.')+'''<ol class="q-list answered stagger"><li><b>Data</b><span>Disclosures explain what is collected and why.</span></li><li><b>Customer commitments</b><span>Refund answers withheld; product and order status only.</span></li><li><b>Jurisdictions</b><span>Singapore customers only in this pilot.</span></li><li><b>Accountability</b><span>Head of Customer Operations owns it; a human reviewer can correct an outcome.</span></li></ol><p class="decision-result"><b>Decision: restrict the pilot.</b> Permit product information and order status.<br>Keep refund decisions with staff until testing and controls justify expansion.</p>''',['R00','R02']),
(30,'TAKEAWAYS','AI Governance implementation roadmap','''<div class="implementation"><article><p class="phase">01 · FOUNDATION</p><h3>Create an AI inventory</h3><ul class="check"><li>Record purpose, owner, users, data, supplier and deployment status</li><li>Assign responsibility for keeping it current</li><li>Address urgent known risks while the inventory is completed</li></ul></article><article><p class="phase">02 · ASSESS AND ESTABLISH CONTROLS</p><h3>Assess uses and establish controls</h3><ul class="check"><li>Identify applicable obligations and the approval authority</li><li>Test performance and human review</li><li>Establish disclosures and supplier requirements</li></ul></article><article><p class="phase">03 · OPERATE AND IMPROVE</p><h3>Monitor and improve</h3><ul class="check"><li>Monitor outcomes, complaints and incidents</li><li>Review material changes and management decisions</li><li>Test rollback or retirement arrangements</li></ul></article></div><p class="implementation-next">Add assurance tools, dedicated resources or certification when risk, scale or contractual needs justify them.</p>''',['R02','R03','R04','R18']),
]
