"""Audience-facing slide compositions for this course.

Narration, sources and the outline live in course.md. Shared components live in
templates/full-decks/course/style.css. Build with scripts/build-course.sh.
"""

SECTION_BOUNDS = [3, 8, 14, 17, 21, 25, 28]

SOURCE_LABELS = {
 'R00': ('Hypothetical example · course teaching synthesis', None),
 'R01': ('OECD · Organisation for Economic Co-operation and Development · 2024 explanatory memorandum', 'https://www.oecd.org/en/publications/explanatory-memorandum-on-the-updated-oecd-definition-of-an-ai-system_623da898-en.html'),
 'R02': ('NIST AI RMF 1.0', 'https://airc.nist.gov/airmf-resources/airmf/5-sec-core/'),
 'R03': ('ISO/IEC 42001:2023', 'https://www.iso.org/standard/42001'),
 'R04': ('Singapore Model AI Governance Framework · second edition, 2020', 'https://www.imda.gov.sg/-/media/imda/files/infocomm-media-landscape/sg-digital/tech-pillars/artificial-intelligence/second-edition-of-the-model-ai-governance-framework.pdf'),
 'R05': ('PDPC · Data Protection Obligations', 'https://www.pdpc.gov.sg/overview-of-pdpa/the-legislation/personal-data-protection-act/data-protection-obligations'),
 'R06': ('Bank of England / FCA · Artificial intelligence in UK financial services · 21 November 2024', 'https://www.bankofengland.co.uk/report/2024/artificial-intelligence-in-uk-financial-services-2024'),
 'R07': ('European Commission · AI Act overview', 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'),
 'R08': ('Official implementation timeline · July 2026 amendment', 'https://ai-act-service-desk.ec.europa.eu/en/ai-act/eu-ai-act-implementation-timeline'),
 'R09': ('UK AI regulation white paper · 2023', 'https://www.gov.uk/government/publications/ai-regulation-a-pro-innovation-approach/white-paper'),
 'R10': ('MAS · Supervisory approach and regulatory instruments', 'https://www.mas.gov.sg/regulation/mas-supervisory-approach-and-regulatory-instruments'),
 'R11': ('FCA · AI approach · February 2026', 'https://www.fca.org.uk/firms/innovation/ai-approach'),
 'R12': ('UK Treasury Committee · January 2026 report', 'https://publications.parliament.uk/pa/cm5901/cmselect/cmtreasy/684/report.html'),
 'R14': ('PDPC · Re HSBC Bank (Singapore) [2021] SGPDPC 3 · paragraphs 17–19', 'https://www.pdpc.gov.sg/-/media/files/pdpc/pdf-files/commissions-decisions/decision--hsbc-bank-singapore-limited--10032021.pdf'),
 'R18': ('MAS P017-2025 §3.4 · consultation proposal, finance-specific', 'https://www.mas.gov.sg/publications/consultations/2025/consultation-paper-on-guidelines-on-artificial-intelligence-risk-management'),
 'R20': ('IMDA · Singapore Digital Economy Report 2025 · data year 2024', 'https://www.imda.gov.sg/assets/e77d879a-6b39-4de4-b024-5e0c6da0eff3.pdf'),
 'R21': ('MAS · Information paper on AI model risk management · 5 December 2024', 'https://www.mas.gov.sg/publications/monographs-or-information-paper/2024/artificial-intelligence-model-risk-management'),
 'R22': ('MAS · AI Risk Management Toolkit · 20 March 2026', 'https://www.mas.gov.sg/news/media-releases/2026/mas-partners-industry-to-develop-ai-risk-management-toolkit-for-the-financial-sector'),
 'R23': ('AI Risk Management Toolkit · gov.uk · 8 September 2026', 'https://www.gov.uk/government/publications/ai-risk-management-toolkit'),
 'R24': ('Malaysia · National Guidelines on AI Governance and Ethics, 2024 · AI Governance Bill consultation, July 2026', 'https://upc.mpc.gov.my/view-consultation/264'),
 'R25': ('Japan · Act on Promotion of R&D and Utilization of AI-Related Technologies, 2025', 'https://laws.e-gov.go.jp/law/507AC0000000053'),
 'R13': ('Garante · Foodinho (Glovo) · November 2024 penalty notice', 'https://www.garanteprivacy.it/home/docweb/-/docweb-display/print/10074840'),
 'R15': ('Moffatt v. Air Canada · 2024 BCCRT 149', 'https://decisions.civilresolutionbc.ca/crt/crtd/en/item/525448/index.do'),
 'R16': ('Zillow Group · Q3 2021 results filing · 2 November 2021', 'https://www.sec.gov/Archives/edgar/data/1617640/000161764021000085/z-20211102.htm'),
 'R17': ('MAS · FEAT principles · 2018, updated 7 February 2019', 'https://www.mas.gov.sg/-/media/MAS/News-and-Publications/Monographs-and-Information-Papers/FEAT-Principles-Updated-7-Feb-19.pdf'),
 'R19': ('MDDI · human accountability for autonomous AI agents · 6 May 2026', 'https://www.mddi.gov.sg/newsroom/mddi-s-response-to-pq-on-ensuring-meaningful-human-accountability-for-public-facing-autonomous-ai-agents-and-pathways-to-mandatory-governance-in-high-risk-sectors/'),
}
CHAT = '''<svg viewBox="0 0 80 80" aria-hidden="true"><path d="M12 13h56v42H36L20 68V55h-8z"/><path d="M24 28h32M24 39h23" fill="none"/></svg>'''

def scenario(text, title="A Singapore retailer's customer-service chatbot"):
    return f'<div class="scenario">{CHAT}<div><span class="case-id">HYPOTHETICAL EXAMPLE</span><h3>{title}</h3><p>{text}</p></div></div>'

def question(options, cls='legal-quiz'):
    rows=[]
    for i,(answer,feedback,correct) in enumerate(options):
        rows.append(f'<button type="button" class="mcq"'+(' data-correct' if correct else '')+f'><span class="letter">{chr(65+i)}</span><span><b>{answer}</b><span class="why">{feedback}</span></span></button>')
    return f'<div class="quiz {cls}" aria-label="Choose one answer">'+''.join(rows)+'<p class="verdict" aria-live="polite"></p></div>'

# Each tuple: course slide, kicker, heading, composition, source IDs.
SLIDES = [
(1,'','AI Governance Overview','''<div class="cover-main"><p class="cover-series">AI for Business Leaders · Online Series for ISCA</p><h1 class="cover-title">AI Governance Overview</h1><div class="cover-rule"></div><p class="cover-by">Ray Han, PhD (Computer Science, NTU)</p><p class="cover-role">Chief AI Trainer, HGT Consultancy Pte Ltd</p></div><div class="cover-foot"><span>ray.han@hgtconsultancy.com</span><span>30 minutes · recorded</span></div>''',[]),
(2,'THE LAUNCH DECISION','Would you approve the launch?',scenario('The supplier says its product follows Singapore’s Model AI Governance Framework.')+question([
('Approve the launch','Supplier alignment alone does not establish readiness.',False),
('Reject the proposal','The available facts do not justify permanent rejection.',False),
('Request more information','Withhold approval and obtain evidence about this deployment.',True)],'decision-quiz'),['R04']),
(3,'BEFORE APPROVAL','Questions to consider first','''<ol class="q-list stagger"><li><b>Data*</b><span>What personal data will the chatbot collect or use?</span></li><li><b>Customer commitments</b><span>What commitments can it make to customers?</span></li><li><b>Jurisdictions</b><span>Which jurisdictions will it serve?</span></li><li><b>Accountability</b><span>Who will be accountable for its operation?</span></li></ol><div class="stagger"><p class="minor-note">*Direct PDPA relevance where personal data is involved. Other questions may also raise data-protection obligations.</p></div>''',['R04','R05']),
(4,'DEFINITION','What is an AI system?','''<p class="definition">A machine-based system that infers from inputs how to produce predictions, content, recommendations or decisions, with varying autonomy, and outputs that can affect the real world.</p><p class="definition-sub">Three types of AI you need to know.</p><div class="grid g3 mt-m stagger"><article class="named-box"><h4>Predictive model</h4><p>Estimates credit risk.</p></article><article class="named-box"><h4>Generative AI</h4><p>Produces a customer reply.</p></article><article class="named-box"><h4>AI agent</h4><p>Acts through software tools.</p></article></div>''',['R01']),
(5,'DEFINITION','What is AI governance?','''<p class="definition">The responsibilities, policies, decision processes and controls through which an organisation oversees AI it builds, buys or uses.</p><p class="definition-sub">It answers three questions.</p><div class="grid g3 mt-m stagger"><article class="named-box"><h4>Who decides?</h4><p>Who approves a use, on what evidence, and when must they reconsider?</p></article><article class="named-box"><h4>What could go wrong?</h4><p>What harm is possible, and which controls reduce it?</p></article><article class="named-box"><h4>What must we meet?</h4><p>Which legal and contractual obligations apply to this use?</p></article></div>''',['R02','R03']),
(6,'SCOPE','Governance covers the AI lifecycle','''<ol class="lifecycle stagger"><li><span class="step-no">01</span><h4>Define</h4><p>Purpose, benefit, affected people and acceptable limits.</p></li><li><span class="step-no">02</span><h4>Develop or procure</h4><p>Data, supplier dependencies and system evidence.</p></li><li><span class="step-no">03</span><h4>Test and approve</h4><p>Intended workflow, safeguards and deployment conditions.</p></li><li><span class="step-no">04</span><h4>Operate and review</h4><p>Outcomes, complaints, incidents and material changes.</p></li><li><span class="step-no">05</span><h4>Retire or replace</h4><p>Access, records and dependent workflows.</p></li></ol><div class="stagger"><p class="review-loop">Reassess whenever the model, data, users or operating context changes.</p></div>''',['R02','R03']),
(7,'IN PRACTICE','Six components of organisational AI governance','''<div class="component-grid stagger reveal-cards"><article class="component"><div><h4>Accountability and oversight</h4><p>Owner, approval authority and escalation.</p></div></article><article class="component"><div><h4>Inventory and impact assessment</h4><p>Uses, purposes, affected people and consequences.</p></div></article><article class="component"><div><h4>Data and supplier governance</h4><p>Privacy, quality, security and supplier responsibilities.</p></div></article><article class="component"><div><h4>Testing and human oversight</h4><p>Acceptable performance and effective intervention.</p></div></article><article class="component"><div><h4>Transparency and recourse</h4><p>Accurate explanations and usable review routes.</p></div></article><article class="component"><div><h4>Monitoring and improvement</h4><p>Outcomes, incidents, changes and retirement.</p></div></article></div>''',['R02','R03','R04']),
(8,'ACCOUNTABILITY','Who reviews an AI proposal before launch?','''<table class="roles"><thead><tr><th>Role</th><th>Question to resolve</th><th>Evidence before approval</th></tr></thead><tbody><tr><td>Business owner</td><td>What is the intended use and acceptable outcome?</td><td>Purpose, boundaries and affected people</td></tr><tr><td>Technical and data teams</td><td>Does the system work acceptably in this setting?</td><td>Test results, limitations and operating controls</td></tr><tr><td>Risk, legal and compliance</td><td>Which obligations apply, and are the safeguards adequate?</td><td>Applicability assessment and independent challenge</td></tr><tr><td>Accountable executive</td><td>Do the evidence and conditions justify deployment?</td><td>Approval record, residual risk and review triggers</td></tr></tbody></table>''',['R02','R03']),
(9,'AS AT 13 SEPTEMBER 2026','AI governance across jurisdictions','''<div class="map-layout"><p class="map-prompt">Assess the use, the affected people, the locations served, and whether the organisation is a provider or a deployer.</p><p class="map-detail">Select a jurisdiction to see its approach.</p><div class="map-stage">{{WORLD_MAP}}</div><div class="map-side"><div class="map-controls">{{MAP_CONTROLS}}</div></div></div>''',['R04','R07','R09','R24','R25']),
(10,'READING THE RULES','Different instruments have different legal effects','''<div class="legal-stack stagger"><div class="legal-row"><h4>Binding requirements</h4><p>Acts, regulations and binding regulatory requirements create duties for the relevant activity.</p></div><div class="legal-row"><h4>Supervisory expectations</h4><p>Guidance may explain existing law or inform supervisory assessment and corrective action.</p></div><div class="legal-row"><h4>Voluntary frameworks</h4><p>Methods and guidance for organising controls. Contracts or policies may add commitments.</p></div></div>''',['R04','R05','R10']),
(11,'AS AT 12 SEPTEMBER 2026','AI Governance in Singapore','''<div class="legal-stack stagger"><div class="legal-row"><h4>Binding requirements</h4><p>The PDPA governs relevant collection, use and disclosure of personal data, subject to its scope and exceptions. Other business and customer obligations may also apply.</p></div><div class="legal-row"><h4>Supervisory expectations</h4><p>Sector instruments add detail where the organisation conducts a regulated activity. A financial institution reviews the relevant MAS requirements and guidance as well.</p></div><div class="legal-row"><h4>Voluntary frameworks</h4><p>The Model AI Governance Framework covers internal governance, human involvement, operations management and stakeholder communication. It does not replace applicable law.</p></div></div>''',['R04','R05','R10']),
(12,'AS AT 12 SEPTEMBER 2026','EU AI Act','''<p class="eu-takeaway">Non-EU organisations can be in scope, including certain uses of AI outputs in the Union.</p><p class="block-label">What the Act regulates</p><div class="eu-components"><article><h4>Prohibited practices</h4><p>Uses the Act bans within its scope.</p></article><article><h4>High-risk systems</h4><p>Risk management, data, records and human oversight.</p></article><article><h4>General-purpose AI</h4><p>Separate obligations for model providers.</p></article><article><h4>Transparency</h4><p>Disclosure for specified AI interactions and content.</p></article></div><div class="stagger"><div class="eu-schedule"><p class="block-label">When each part applies</p><ol class="timeline"><li><time>2 February 2025</time><p>Prohibitions</p></li><li><time>2 August 2025</time><p>General-purpose AI provisions</p></li><li><time>2 August 2026</time><p>General application, including Article 50</p></li><li class="future"><time>2 December 2027</time><p>Annex III high-risk requirements</p></li><li class="future"><time>2 August 2028</time><p>Annex I product-related high-risk requirements</p></li></ol></div></div>''',['R07','R08']),
(14,'CHECK YOUR UNDERSTANDING','Does following a framework resolve the data issue?','''<p class="quiz-stem">The retailer collects contact details and purchase histories to personalise offers, and has not explained those purposes. The supplier follows the Model AI Governance Framework and displays an AI label. Assume the PDPA notification obligation applies.</p>'''+question([
('Yes. Following the framework resolves it.','Framework alignment does not establish that the retailer met its obligation.',False),
('No. Address the applicable PDPA obligation before launch.','The retailer must explain the relevant data-use purposes.',True),
('Yes. The AI label is enough.','An AI label alone does not explain the data-use purposes.',False)]),['R04','R05']),
(16,'CASE STUDY · TRANSPARENCY AND RECOURSE','HSBC’s credit-assessment disclosures','''<blockquote class="case-quote lead-box"><p>&ldquo;From the perspective of <mark>accountability and disclosure</mark> of policies and practices, HSBC had acquitted itself.&rdquo;</p><cite>Deputy Commissioner for Personal Data Protection, Singapore &middot; paragraph 19</cite></blockquote><div class="case-timeline"><article><h4>The case</h4><p>In 2018 an unsuccessful credit-card applicant asked HSBC Singapore for its internal evaluation report. The bank supplied it with specified information redacted, and the dispute reached the Commission.</p></article><article><h4>10 March 2021 &middot; the decision</h4><p>The evaluative-purpose exception supported withholding the specified data. HSBC also supplied its policies on data and AI use in credit assessment.</p></article></div>''',['R14']),
(24,'THE SAME FOUR QUESTIONS, ANSWERED','Would you approve the chatbot now?',scenario('The team has supplied evidence. Refund-policy answers have not passed the retailer’s acceptance tests.')+'''<ol class="q-list answered"><li><b>Data</b><span>Disclosures explain what is collected and why.</span></li><li><b>Customer commitments</b><span>Refund answers withheld; product and order status only.</span></li><li><b>Jurisdictions</b><span>Singapore customers only in this pilot.</span></li><li><b>Accountability</b><span>Head of Customer Operations owns it; a human reviewer can correct an outcome.</span></li></ol><div class="decision-review"><button type="button">What is the right decision here?</button><p class="answer"><b>Restrict the pilot.</b> Permit product information and order status. Keep refund decisions with staff until testing and controls justify expansion.</p></div>''',['R00','R02']),
(13,'INVENTORY AND IMPACT','Applicable obligations and potential harm are different questions','''<div class="grid g2"><article class="concept-box"><h4>Which duties apply?</h4><p class="dim">The obligations and supervisory expectations relevant to this use.</p></article><article class="concept-box"><h4>What harm is possible?</h4><p class="dim">Who could be harmed, how severely, how likely, and whether it can be corrected.</p></article></div><p class="definition-sub">Compare two uses in the same retailer.</p><ul class="plain-compare"><li><b>Drafting a meeting summary.</b> An employee checks it before circulating, so the effect is contained.</li><li><b>Automatically refusing refunds.</b> This directly affects customers, so the decision and review arrangements need closer examination.</li></ul><p class="minor-note">A voluntary framework label does not tell an approver which use presents the greater risk.</p>''',['R00','R02','R05']),
(15,'CASE STUDY · TRANSPARENCY AND RECOURSE','Foodinho: no usable route to contest','''<div class="lead-box">The Italian data-protection authority&rsquo;s notice described an automated message sent when an account was blocked. It did not tell riders how to <mark>contest the decision</mark> or ask for the account to be restored.</div><div class="case-timeline"><article><h4>The case</h4><p>Foodinho, in the Glovo group, managed delivery riders in Italy through a digital platform. Riders received an automated message when an account was blocked or deactivated.</p></article><article><h4>November 2024 &middot; the penalty</h4><p>The authority imposed a five-million-euro penalty for unlawful processing of riders&rsquo; data. Several infringements were involved, not one missing feature.</p></article></div>''',['R13','R00']),
(17,'CASE STUDY · MONITORING AND IMPROVEMENT','Consequence is broader than a regulatory fine','''<div class="lead-box">Neither outcome involved a regulator: one was a <mark>customer claim</mark>, the other a <mark>business loss</mark>.</div><div class="case-timeline"><article><h4>Air Canada &middot; a customer claim</h4><p>A chatbot gave incorrect information about bereavement fares. The British Columbia Civil Resolution Tribunal held the airline responsible for the misleading information.</p></article><article><h4>Zillow &middot; an inventory loss</h4><p>The 2021 filing reported a 304.4 million US dollar write-down on Zillow Offers, citing pricing unpredictability and capacity constraints rather than a defective algorithm.</p></article></div>''',['R15','R16','R00']),
(18,'SECTOR APPLICATION','Financial Sector in Singapore','''<div class="lead-box">Connect AI controls to existing governance, risk and compliance arrangements, and distinguish <mark>binding requirements</mark>, advisory principles and proposals rather than treating every MAS publication as having the same legal effect.</div><div class="legal-stack"><div class="legal-row"><div><h4>FEAT principles</h4><span class="status">Advisory &middot; first published 2018</span></div><p>Fairness, Ethics, Accountability and Transparency in the use of AI and data analytics.</p></div><div class="legal-row"><div><h4>Guidelines on AI Risk Management</h4><span class="status">Consultation proposal &middot; November 2025</span></div><p>Proposes an AI inventory and proportionate risk management across the lifecycle. A proposal, not an issued rule.</p></div></div>''',['R10','R17','R18']),
(19,'SECTOR APPLICATION','Financial Sector in the United Kingdom','''<div class="legal-row stagger-item"><h4>Existing frameworks apply</h4><p>The FCA identifies the Consumer Duty and senior-management accountability as relevant foundations for firms&rsquo; use of AI.</p></div><div class="legal-row stagger-item"><h4>Existing powers apply</h4><p>The regulator can use its supervisory and enforcement powers where a firm&rsquo;s use of AI breaches relevant financial regulatory requirements.</p></div><div class="callout mt-l">Responsibilities follow the firm&rsquo;s activities and its documented management arrangements. <b>Avoid assigning all AI risk to the chief technology officer, or creating a new title without decision authority.</b></div>''',['R11','R12','R00']),
(20,'BEYOND FINANCE','Apply these governance practices in your sector','''<ol class="q-list stagger"><li><b>Map obligations</b><span>Start with the activity your organisation performs, and identify the requirements already attached to it.</span></li><li><b>Assign responsibility</b><span>An accountable owner, and an appropriate independent review.</span></li><li><b>Retain evidence</b><span>Testing, decisions and monitoring, so management can see whether controls are working.</span></li></ol><p class="minor-note">For a retailer this may involve customer communications, personal data and refund decisions. For an employer, recruitment and review of consequential decisions. These are questions to investigate, not a claim that identical duties apply.</p>''',['R00','R02','R03']),
(22,'YOUR ROLE','Three questions, and the evidence to request','''<table class="roles"><thead><tr><th>Question</th><th>Evidence to request</th></tr></thead><tbody><tr><td>Who is accountable for this use?</td><td>A named owner, a decision authority and an escalation route</td></tr><tr><td>How can an affected person challenge an outcome?</td><td>The review procedure, and evidence that someone can change the decision</td></tr><tr><td>What have we told people about the system?</td><td>Accurate explanations of purpose, limitations and use of data</td></tr></tbody></table><p class="minor-note">Foodinho illustrates the importance of a usable challenge route; HSBC illustrates disclosure alongside legal access limits. Different lessons, not one universal explainability requirement.</p>''',['R00','R13','R14','R11']),
(23,'TESTING AND HUMAN OVERSIGHT','What evidence is needed before approval?','''<ol class="q-list stagger"><li><b>Testing in the intended setting</b><span>Relevant users and foreseeable failure conditions, not a supplier benchmark alone.</span></li><li><b>A person who can intervene</b><span>With the authority, information and time to do so.</span></li><li><b>Production monitoring</b><span>What it detects, who receives alerts, and when escalation is required.</span></li><li><b>A tested way to stop</b><span>Stop, restrict or roll back &mdash; tried, not assumed.</span></li></ol><div class="callout mt-l">Singapore&rsquo;s agentic guidance recommends human review for high-stakes or irreversible actions. <b>This is voluntary guidance, not a general statutory prohibition.</b></div>''',['R00','R02','R03','R19']),
(26,'INVENTORY AND IMPACT','Record the next decision for each priority AI use','''<ol class="q-list answered"><li><b>Use case</b><span>Complaints triage &middot; hypothetical</span></li><li><b>Accountable owner</b><span>Head of Customer Operations</span></li><li><b>Review route</b><span>Some escalated complaints close without human review</span></li><li><b>Evidence</b><span>Supplier test data only</span></li><li><b>Next decision, and by when</b><span>Whether a controlled pilot can proceed once those gaps are addressed</span></li></ol><p class="minor-note">Link the record to the relevant inventory entry and assessment. Where a field is incomplete, record the action, the responsible person and the deadline &mdash; that gives management a specific issue to follow up.</p>''',['R00','R02','R03']),
(21,'CHECK YOUR UNDERSTANDING','Who must own this before launch?','''<p class="quiz-stem">A UK-regulated bank is preparing a vendor-built credit-decisioning tool. Its documented management responsibilities place this lending activity with an existing senior manager. The vendor says it tests the model; the bank&rsquo;s risk function has not reviewed the deployment.</p>'''+question([
('The vendor. It tests and monitors the model.','Supplier responsibilities matter and do not replace the bank&rsquo;s own obligations.',False),
('The responsible senior manager, with the bank&rsquo;s review completed first.','Responsibility follows the firm&rsquo;s documented management arrangements for this activity.',True),
('Nobody yet. An AI-specific role must be created first.','The FCA relies on existing accountability rather than a new AI title.',False)]),['R00','R11','R12']),
(25,'CHECK YOUR UNDERSTANDING','Approve, restrict or pause?','''<p class="quiz-stem">An insurance tool flags claims for manual review. It has an owner, a review procedure and accurate customer information. Testing has used only a supplier benchmark. There is no production monitoring and no rollback process.</p>'''+question([
('Approve production use.','The stated gaps would remain unresolved.',False),
('Run an unrestricted pilot.','Calling a deployment a pilot does not establish the missing safeguards.',False),
('Pause production and establish the safeguards.','A bounded pilot may follow, once testing, monitoring, human review and rollback are in place.',True)]),['R00','R02','R03']),
(27,'CHECK YOUR UNDERSTANDING','Which action should come first?','''<p class="quiz-stem">A firm has completed its AI inventory. Next week it plans to activate a tool that automatically declines insurance claims. There is no appeals route and no production monitoring. The board has also asked about ISO certification.</p>'''+question([
('Begin ISO certification.','Certification may provide assurance, and it does not resolve next week&rsquo;s control gap.',False),
('Pause the launch and establish the missing controls.','The known exposure is the automatic decline with no appeals route or monitoring.',True),
('Extend the inventory to every remaining use.','Worth doing, and it does not address this known exposure.',False)]),['R00','R02','R03']),
(28,'TAKEAWAYS','AI Governance implementation roadmap','''<div class="onepager">
  <section class="op-recall">
    <div class="op-block"><p class="op-label">Lifecycle · 5 steps</p><ol class="op-mini"><li>Define</li><li>Develop or procure</li><li>Test and approve</li><li>Operate and review</li><li>Retire or replace</li></ol></div>
    <div class="op-block"><p class="op-label">Components · 6</p><ol class="op-mini"><li>Accountability and oversight</li><li>Inventory and impact assessment</li><li>Data and supplier governance</li><li>Testing and human oversight</li><li>Transparency and recourse</li><li>Monitoring and improvement</li></ol></div>
    <div class="op-block"><p class="op-label">Ask of any proposal · 3</p><ol class="op-mini"><li>Who is accountable for this use?</li><li>How can an affected person challenge an outcome?</li><li>What have we told people about the system?</li></ol></div>
  </section>
  <div class="implementation">
    <article><p class="phase">01 · FOUNDATION</p><h3>Create an AI inventory</h3><ul class="check"><li>Record purpose, owner, users, data, supplier and deployment status</li><li>Assign responsibility for keeping it current</li><li>Address urgent known risks while the inventory is completed</li></ul></article>
    <article><p class="phase">02 · ASSESS AND ESTABLISH CONTROLS</p><h3>Assess uses and establish controls</h3><ul class="check"><li>Identify applicable obligations and the approval authority</li><li>Test performance and human review</li><li>Establish disclosures and supplier requirements</li></ul></article>
    <article><p class="phase">03 · OPERATE AND IMPROVE</p><h3>Monitor and improve</h3><ul class="check"><li>Monitor outcomes, complaints and incidents</li><li>Review material changes and management decisions</li><li>Test rollback or retirement arrangements</li></ul></article>
  </div>
</div><p class="implementation-next">Add assurance tools, dedicated resources or certification when risk, scale or contractual needs justify them.</p>''',['R02','R03','R04','R18']),
]


# Slides waiting on Ray. The label is drawn on the slide, top right under the
# number, so a review pass can be done from the deck rather than from a list.
# Clear an entry when the item is settled; the label disappears with it.
# PROMOTE: if a second course wants this, it belongs in engine.py.
REVIEW = {
 17: 'Air Canada primary source unverified (R15) &middot; lower frame still empty',
 18: 'MAS guidelines issuance status unverified (R18) &middot; lower frame empty',
 21: 'Layout &middot; lower frame still empty',
 28: 'MAS guidelines issuance status unverified (R18)',
}

SLIDES = [(n, k, t, ('<p class="review-flag">Review &middot; ' + REVIEW[n] + '</p>' + b) if n in REVIEW else b, r)
          for n, k, t, b, r in SLIDES]
