#!/usr/bin/env bash
# html-ppt :: assemble-course.sh — sections/*.html -> index.html
#
# Usage:
#   assemble-course.sh <course-dir>            # self-contained (default)
#   assemble-course.sh <course-dir> --linked   # <link>/<script> to ../../assets
#
# Default output is ONE self-contained file: all CSS and JS inlined, no local
# subresources. A Course is a deliverable — it gets emailed, copied to a share
# drive, and opened on someone else's machine. Two things break a linked build:
# Safari refuses to load file:// subresources from PARENT directories, so
# ../../assets/* silently yields an unstyled page; and moving the file out of
# this repo breaks every path. Only webfonts stay remote, and every token stack
# declares a local fallback.
#
# --linked keeps the old behaviour for authoring, where T-key theme cycling
# needs real theme files on disk. Never ship a --linked build.
#
# Reads flat frontmatter from <course-dir>/course.md for title/theme/template.
# Regenerating one Section means rewriting one fragment and re-running this —
# the rest of the course is never read. See docs/adr/0002.

set -euo pipefail

DIR="${1:-}"
MODE="${2:-}"
if [[ -z "$DIR" ]]; then
  echo "usage: assemble-course.sh <course-dir> [--linked]" >&2
  exit 1
fi
DIR="${DIR%/}"
MD="$DIR/course.md"
SECTIONS="$DIR/sections"
HERE="$(cd "$(dirname "$0")/.." && pwd)"

[[ -f "$MD" ]]       || { echo "error: $MD not found" >&2; exit 1; }
[[ -d "$SECTIONS" ]] || { echo "error: $SECTIONS not found" >&2; exit 1; }

fm() {
  awk -v key="$1" '
    NR==1 && $0=="---" { inb=1; next }
    inb && $0=="---"   { exit }
    inb {
      i=index($0,":")
      if (i>0) {
        k=substr($0,1,i-1); v=substr($0,i+1)
        gsub(/^[ \t]+|[ \t]+$/,"",k); gsub(/^[ \t]+|[ \t]+$/,"",v)
        if (k==key) { print v; exit }
      }
    }' "$MD"
}

TITLE="$(fm title)";        TITLE="${TITLE:-Course}"
THEME="$(fm theme)";        THEME="${THEME:-course-warm}"
THEMES="$(fm themes)";      THEMES="${THEMES:-$THEME}"
TEMPLATE="$(fm template)";  TEMPLATE="${TEMPLATE:-course}"
LANG_="$(fm lang)";         LANG_="${LANG_:-en}"

A="$HERE/assets"
T="$HERE/templates/full-decks/$TEMPLATE"
for f in "$A/fonts.css" "$A/base.css" "$A/themes/$THEME.css" \
         "$A/animations/animations.css" "$T/style.css" \
         "$A/runtime.js" "$A/quiz.js" "$A/stage.js"; do
  [[ -f "$f" ]] || { echo "error: missing asset $f" >&2; exit 1; }
done

shopt -s nullglob
FRAGMENTS=("$SECTIONS"/*.html)
shopt -u nullglob
[[ ${#FRAGMENTS[@]} -gt 0 ]] || { echo "error: no fragments in $SECTIONS" >&2; exit 1; }

OUT="$DIR/index.html"

{
  echo '<!DOCTYPE html>'
  echo "<html lang=\"$LANG_\">"
  echo '<head>'
  echo '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
  echo "<title>$TITLE</title>"
  echo "<!-- GENERATED by scripts/assemble-course.sh — do not edit."
  echo "     Narration and outline: course.md · Slides: sections/*.html -->"

  if [[ "$MODE" == "--linked" ]]; then
    R="../../assets"
    echo "<link rel=\"stylesheet\" href=\"$R/fonts.css\">"
    echo "<link rel=\"stylesheet\" href=\"$R/base.css\">"
    echo "<link rel=\"stylesheet\" id=\"theme-link\" href=\"$R/themes/$THEME.css\">"
    echo "<link rel=\"stylesheet\" href=\"$R/animations/animations.css\">"
    echo "<link rel=\"stylesheet\" href=\"../../templates/full-decks/$TEMPLATE/style.css\">"
    echo '</head>'
    echo "<body class=\"tpl-$TEMPLATE stage-fixed\" data-themes=\"$THEMES\" data-theme-base=\"$R/themes/\">"
  else
    # @import rules must precede every other rule, so fonts.css goes first.
    echo '<style>'
    cat "$A/fonts.css"
    echo "/* --- base.css --- */";              cat "$A/base.css"
    echo "/* --- theme: $THEME --- */";         cat "$A/themes/$THEME.css"
    echo "/* --- animations --- */";            cat "$A/animations/animations.css"
    echo "/* --- template: $TEMPLATE --- */";   cat "$T/style.css"
    echo '</style>'
    echo '</head>'
    # No data-themes: with the theme inlined there are no files for the T key to
    # swap to, so the key stays inert rather than breaking the page.
    echo "<body class=\"tpl-$TEMPLATE stage-fixed\">"
  fi

  echo '<div class="deck">'
  for f in "${FRAGMENTS[@]}"; do
    echo ""
    echo "<!-- section: $(basename "$f") -->"
    cat "$f"
  done
  echo ""
  echo '</div>'

  if [[ "$MODE" == "--linked" ]]; then
    echo "<script src=\"../../assets/runtime.js\"></script>"
    echo "<script src=\"../../assets/quiz.js\"></script>"
    echo "<script src=\"../../assets/stage.js\"></script>"
  else
    echo '<script>'; cat "$A/runtime.js"; echo '</script>'
    echo '<script>'; cat "$A/quiz.js";    echo '</script>'
    echo '<script>'; cat "$A/stage.js";   echo '</script>'
  fi
  echo '</body></html>'
} > "$OUT"

SLIDES="$(grep -o 'class="slide[ "]' "$OUT" | wc -l | tr -d ' ')"
KB="$(( $(wc -c < "$OUT") / 1024 ))"
if [[ "$MODE" == "--linked" ]]; then
  echo "✔ $OUT — ${#FRAGMENTS[@]} section(s), $SLIDES slide(s), theme $THEME, ${KB}KB (LINKED — do not ship)"
else
  echo "✔ $OUT — ${#FRAGMENTS[@]} section(s), $SLIDES slide(s), theme $THEME, ${KB}KB self-contained"
fi
