#!/usr/bin/env bash
# html-ppt :: assemble-course.sh — sections/*.html -> index.html
#
# Usage:
#   assemble-course.sh <course-dir>
#
# Reads the flat frontmatter of <course-dir>/course.md for title/theme/template,
# concatenates sections/*.html in filename order, and writes index.html.
# Regenerating one Section means rewriting one fragment and re-running this —
# the rest of the course is never read. See docs/adr/0002.

set -euo pipefail

DIR="${1:-}"
if [[ -z "$DIR" ]]; then
  echo "usage: assemble-course.sh <course-dir>" >&2
  exit 1
fi
DIR="${DIR%/}"
MD="$DIR/course.md"
SECTIONS="$DIR/sections"

[[ -f "$MD" ]]       || { echo "error: $MD not found" >&2; exit 1; }
[[ -d "$SECTIONS" ]] || { echo "error: $SECTIONS not found" >&2; exit 1; }

# flat `key: value` lookup, frontmatter only (first --- ... --- block)
fm() {
  awk -v key="$1" '
    NR==1 && $0=="---" { inb=1; next }
    inb && $0=="---"   { exit }
    inb {
      i=index($0,":")
      if (i>0) {
        k=substr($0,1,i-1); v=substr($0,i+1)
        gsub(/^[ \t]+|[ \t]+$/,"",k); gsub(/^[ \t]+|[ \t]+$/,"",v)
        if (k==key) { print v; exit }
      }
    }' "$MD"
}

TITLE="$(fm title)";        TITLE="${TITLE:-Course}"
THEME="$(fm theme)";        THEME="${THEME:-course-warm}"
THEMES="$(fm themes)";      THEMES="${THEMES:-$THEME}"
TEMPLATE="$(fm template)";  TEMPLATE="${TEMPLATE:-course}"
LANG_="$(fm lang)";         LANG_="${LANG_:-en}"

shopt -s nullglob
FRAGMENTS=("$SECTIONS"/*.html)
shopt -u nullglob
if [[ ${#FRAGMENTS[@]} -eq 0 ]]; then
  echo "error: no fragments in $SECTIONS" >&2
  exit 1
fi

# courses/<name>/index.html sits two deep, same as examples/<name>/ — so the
# asset prefix matches what every other deck in the repo uses. See docs/adr/0001.
A="../../assets"
T="../../templates/full-decks/$TEMPLATE"
OUT="$DIR/index.html"

{
  echo '<!DOCTYPE html>'
  echo "<html lang=\"$LANG_\">"
  echo '<head>'
  echo '<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
  echo "<title>$TITLE</title>"
  echo "<!-- GENERATED by scripts/assemble-course.sh — do not edit."
  echo "     Narration and outline: course.md · Slides: sections/*.html -->"
  echo "<link rel=\"stylesheet\" href=\"$A/fonts.css\">"
  echo "<link rel=\"stylesheet\" href=\"$A/base.css\">"
  echo "<link rel=\"stylesheet\" id=\"theme-link\" href=\"$A/themes/$THEME.css\">"
  echo "<link rel=\"stylesheet\" href=\"$A/animations/animations.css\">"
  echo "<link rel=\"stylesheet\" href=\"$T/style.css\">"
  echo '</head>'
  echo "<body class=\"tpl-$TEMPLATE\" data-themes=\"$THEMES\" data-theme-base=\"$A/themes/\">"
  echo '<div class="deck">'
  for f in "${FRAGMENTS[@]}"; do
    echo ""
    echo "<!-- section: $(basename "$f") -->"
    cat "$f"
  done
  echo ""
  echo '</div>'
  echo "<script src=\"$A/runtime.js\"></script>"
  echo "<script src=\"$A/quiz.js\"></script>"
  echo '</body></html>'
} > "$OUT"

# 'class="slide' alone also matches class="slide-number"; require a
# delimiter so `slide` and `slide full` count and `slide-number` does not.
SLIDES="$(grep -o 'class="slide[ "]' "$OUT" | wc -l | tr -d ' ')"
echo "✔ $OUT — ${#FRAGMENTS[@]} section(s), $SLIDES slide(s), theme $THEME"
